services:
  - type: web
    name: django-blog
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn Blog.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: Blog.settings
      - key: PYTHON_VERSION
        value: 3.11
      - key: SECRET_KEY
        generateValue: true
      - key: CLOUDINARY_CLOUD_NAME
        value: your_cloud_name
      - key: CLOUDINARY_API_KEY
        value: your_api_key
      - key: CLOUDINARY_API_SECRET
        value: your_api_secret
    staticPublishPaths:
      - source: staticfiles
        publishPath: /static
